### ISSUE TITLE
Allow to rename a downloaded file

### ISSUE THREAD

**Issue by Vince1171** [ubports/ubports-installer#1611]
It would allow to do something like
```yml
          - core:download:
             conditions:
                - var : "version"
                - value : "16"
              group: "firmware"
              files:
                - url: "https://somewebsite.xyz/rootfs-16.img"
                - output : "someName.img"

          - core:download:
             conditions:
                - var : "version"
                - value : "17"
              group: "firmware"
              files:
                - url: "https://somewebsite.xyz/rootfs-17.img"
                - output : "someName.img"

           - fastboot:flash:
              partitions:
                - partition: "recovery"
                  file: "someName.img"
                  group: "firmware"

          - fastboot:boot:
              group: "firmware"
              file: "someName.img"
```
instead of
```yml
          - core:download:
             conditions:
                - var : "version"
                - value : "16"
              group: "firmware"
              files:
                - url: "https://somewebsite.xyz/rootfs-16.img"

          - core:download:
             conditions:
                - var : "version"
                - value : "17"
              group: "firmware"
              files:
                - url: "https://somewebsite.xyz/rootfs-17.img"

           - fastboot:flash:
               conditions:
                - var : "version"
                - value : "16"
              partitions:
                - partition: "recovery"
                  file: "rootfs-16.img"
                  group: "firmware"

            - fastboot:flash:
               conditions:
                - var : "version"
                - value : "17"
              partitions:
                - partition: "recovery"
                  file: "rootfs-17.img"
                  group: "firmware"

          - fastboot:boot:
              conditions:
                - var : "version"
                - value : "16"
              group: "firmware"
              file: "rootfs-16.img"

          - fastboot:boot:
              conditions:
                - var : "version"
                - value : "17"
              group: "firmware"
              file: "rootfs-17.img"
```
it avoid repetition
