### ISSUE TITLE
Ensure recovery supports installing Ubuntu Touch

### ISSUE THREAD

**Issue by amartinz** [ubports/ubports-installer#2505]
See: https://github.com/ubports/halium_bootable_recovery/issues/22

**Comment by NeoTheThird** [comment]
recoveries are updated over systemimage, right? so we can assume it to be there after the next ota? we'll probably also have to update some configs (eg https://github.com/ubports/installer-configs/blob/master/v2/devices/FP2.yml#L48) to make sure we're downloading the right version.

**Comment by amartinz** [comment]
this depends on the device.

what do you think about adding a new method to call in the installer config to verify recovery?
devices with supported recovery could then opt-in to check recovery.

until most devices are updated and we can move the check to be opt-out.

**Comment by NeoTheThird** [comment]
Some prerequisites for this in https://github.com/ubports/promise-android-tools/pull/61.

Making it opt-in during the rollout is a good idea. I can imagine two ways this could be done.

a) The `systemimage:install` step could be given an optional `verify_recovery` property, which could trigger a global handler
```yml
      - actions:
          - systemimage:install:
                verify_recovery: true
```

b) A special `systemimage:assert_capable_recovery` step or generic `adb:assert_prop` step
```yml
      - actions:
          - adb:assert_prop:
              property: "ro.ubuntu.recovery"
              value: "true"
          - systemimage:assert_capable_recovery:
        fallback:
          - <steps needed to install a capable recovery>
```
