### ISSUE TITLE
fastboot:reboot* should be similar to adb:reboot to_state

### ISSUE THREAD

**Issue by JamiKettunen** [ubports/ubports-installer#2837]
Similar to
```yaml
      - actions:
          - adb:reboot:
              to_state: "recovery"
```
the following should also work
```yaml
      - actions:
          - fastboot:reboot:
              to_state: "recovery"
```
As it stands you have to use
```yaml
      - actions:
          - fastboot:reboot_recovery:
```
and the same is also true for `fastboot:reboot_fastboot` and `fastboot:reboot_bootloader`.

Is there any reason `adb:reboot` and `fastboot:reboot` *should* work differently with regard to booting to different states?
